import "./globals.css";
import "swiper/css";
import { CartContextProvider } from "@/_api/cartContext";
import { QueryProvider } from "@/_components/shared/query-provider";
import { Header } from "@/_components/shared/header/header";
import localFont from "next/font/local";
import { CTAFooter } from "@/_components/shared/footer/cta-footer";
import { Footer } from "@/_components/shared/footer/footer";
import { NavigationMobile } from "@/_components/shared/header/NavigationMobile";
import Script from "next/script";
import { UserProvider } from "@/_context/user-context";
import { ToastContainer } from "react-toastify";
import { Scroll } from "@/_components/scroll-to-top";
import { CookieAlert } from "@/_components/shared/cookies";

export const metadata = {
  title: "Alesari",
  description: "Generated by create next app",
};

const old_standard = localFont({
  src: [
    {
      path: "../lib/font/oldstandard-regular.ttf",
      weight: "400",
    },
    {
      path: "../lib/font/oldstandard-bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-oldstandard",
});

const century_schoolbook = localFont({
  src: [
    {
      path: "../lib/font/century.ttf",
      weight: "400",
    },
  ],
  variable: "--font-century",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          crossOrigin="anonymous"
          src="https://kit.fontawesome.com/f141ac3909.js"
        />
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
          {/* GTM script - ubaci ovde */}
          <Script id="gtm-script" strategy="afterInteractive">
          {`
          (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':

new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],

j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=

'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);

})(window,document,'script','dataLayer','GTM-56MFRTQF');
          `}
        </Script>
      </head>
      <body
        className={`${old_standard?.variable} ${century_schoolbook?.variable} !min-h-dvh`}
      >
         {/* GTM noscript - ubaci odmah posle otvaranja body */}
         <noscript>
         <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-56MFRTQF"

height="0" width="0" style="display:none;visibility:hidden"></iframe>
        </noscript>
        <CartContextProvider>
          <UserProvider>
            <QueryProvider>
              <Header />
              <NavigationMobile />
              {children}
              <CTAFooter />
              <Footer />
            </QueryProvider>
          </UserProvider>
        </CartContextProvider>
        <Scroll />
        <CookieAlert />
      </body>
    </html>
  );
}
